apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: laravel
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.3
        env:
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: database_user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database_password
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database_root_password
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: database_name
