apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
  namespace: phpmyadmin 
data:
  database_user: user1
  database_name: lav1
  database_host: mariadb-service.laravel.svc.cluster.local
  database_port: "3306"